POST http://localhost:3001/authenticate
Content-Type: application/json

{
  "id": "Gato Cat",
  "name": "Gato Cat",
  "custom": {
    "externalId": "Gato Cat",
    "profileUrl": "https://www.example.com/avatar.jpg"
  }
}